// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoSortLine: typeof import('./src/components/Result/AutoSortLine.vue')['default']
    BasicDescription: typeof import('./src/components/Result/BasicDescription.vue')['default']
    BicolorPie: typeof import('./src/components/Result/BicolorPie.vue')['default']
    CodeLenDescription: typeof import('./src/components/Result/CodeLenDescription.vue')['default']
    CodeLenDistBar: typeof import('./src/components/Result/CodeLenDistBar.vue')['default']
    CollisionDescription: typeof import('./src/components/Result/CollisionDescription.vue')['default']
    CollisionDistBar: typeof import('./src/components/Result/CollisionDistBar.vue')['default']
    CombsDescription: typeof import('./src/components/Result/CombsDescription.vue')['default']
    CombsDistBar: typeof import('./src/components/Result/CombsDistBar.vue')['default']
    ComparedBars: typeof import('./src/components/Result/comparedBars.vue')['default']
    FingerHeatMap: typeof import('./src/components/FingerHeatMap.vue')['default']
    FingerPie: typeof import('./src/components/Result/FingerPie.vue')['default']
    FingersDescription: typeof import('./src/components/Result/FingersDescription.vue')['default']
    HandComp: typeof import('./src/components/Result/HandComp.vue')['default']
    HandsDescription: typeof import('./src/components/Result/HandsDescription.vue')['default']
    HeatMap: typeof import('./src/components/HeatMap.vue')['default']
    KeyHeatSorted: typeof import('./src/components/Result/KeyHeatSorted.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MultiResult: typeof import('./src/components/MultiResult.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFlex: typeof import('naive-ui')['NFlex']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    Result: typeof import('./src/components/Result/Result.vue')['default']
    ResultBasic: typeof import('./src/components/Result/ResultBasic.vue')['default']
    ResultKeyHeat: typeof import('./src/components/Result/ResultKeyHeat.vue')['default']
    Show: typeof import('./src/components/Show.vue')['default']
    WordsDescription: typeof import('./src/components/Result/WordsDescription.vue')['default']
    WordsDistBar: typeof import('./src/components/Result/WordsDistBar.vue')['default']
  }
}
