// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AutoSortLine: (typeof import("./src/components/Result/AutoSortLine.vue"))["default"];
    BasicDescription: (typeof import("./src/components/Result/BasicDescription.vue"))["default"];
    BicolorPie: (typeof import("./src/components/Result/BicolorPie.vue"))["default"];
    CodeLenDescription: (typeof import("./src/components/Result/CodeLenDescription.vue"))["default"];
    CodeLenDistBar: (typeof import("./src/components/Result/CodeLenDistBar.vue"))["default"];
    CollisionDescription: (typeof import("./src/components/Result/CollisionDescription.vue"))["default"];
    CollisionDistBar: (typeof import("./src/components/Result/CollisionDistBar.vue"))["default"];
    CombsDescription: (typeof import("./src/components/Result/CombsDescription.vue"))["default"];
    CombsDistBar: (typeof import("./src/components/Result/CombsDistBar.vue"))["default"];
    ComparedBars: (typeof import("./src/components/Result/comparedBars.vue"))["default"];
    FingerPie: (typeof import("./src/components/Result/FingerPie.vue"))["default"];
    FingersDescription: (typeof import("./src/components/Result/FingersDescription.vue"))["default"];
    HandComp: (typeof import("./src/components/Result/HandComp.vue"))["default"];
    HandsDescription: (typeof import("./src/components/Result/HandsDescription.vue"))["default"];
    KeyHeatSorted: (typeof import("./src/components/Result/KeyHeatSorted.vue"))["default"];
    Main: (typeof import("./src/components/Main.vue"))["default"];
    NButton: (typeof import("naive-ui"))["NButton"];
    NCard: (typeof import("naive-ui"))["NCard"];
    NDivider: (typeof import("naive-ui"))["NDivider"];
    NDrawer: (typeof import("naive-ui"))["NDrawer"];
    NDrawerContent: (typeof import("naive-ui"))["NDrawerContent"];
    NFlex: (typeof import("naive-ui"))["NFlex"];
    NIcon: (typeof import("naive-ui"))["NIcon"];
    NInput: (typeof import("naive-ui"))["NInput"];
    NInputNumber: (typeof import("naive-ui"))["NInputNumber"];
    NMessageProvider: (typeof import("naive-ui"))["NMessageProvider"];
    NRadio: (typeof import("naive-ui"))["NRadio"];
    NRadioGroup: (typeof import("naive-ui"))["NRadioGroup"];
    NSelect: (typeof import("naive-ui"))["NSelect"];
    NSwitch: (typeof import("naive-ui"))["NSwitch"];
    NTag: (typeof import("naive-ui"))["NTag"];
    NText: (typeof import("naive-ui"))["NText"];
    NUpload: (typeof import("naive-ui"))["NUpload"];
    NUploadDragger: (typeof import("naive-ui"))["NUploadDragger"];
    Result: (typeof import("./src/components/Result/Result.vue"))["default"];
    ResultBasic: (typeof import("./src/components/Result/ResultBasic.vue"))["default"];
    ResultKeyHeat: (typeof import("./src/components/Result/ResultKeyHeat.vue"))["default"];
    Text: (typeof import("./src/components/Text.vue"))["default"];
    WordsDescription: (typeof import("./src/components/Result/WordsDescription.vue"))["default"];
    WordsDistBar: (typeof import("./src/components/Result/WordsDistBar.vue"))["default"];
  }
}
