// Generated by https://quicktype.io

export interface Data {
  Info: Info;
  Commit: Commit;
  Pair: Pair;
  Keys: { [key: string]: Key };
  Han: Han;
  Dist: Dist;
  CodeLen: CodeLen;
  LeftHand: number;
  RightHand: number;
  Equivalent: number;
}

export interface CodeLen {
  Total: number;
  PerChar: number;
}

export interface Commit {
  Count: number;
  Word: number;
  WordChars: number;
  WordFirst: number;
  Collision: number;
  CollisionChars: number;
}

export interface Dist {
  CodeLen: number[];
  WordLen: number[];
  Collision: number[];
  Finger: number[];
}

export interface Han {
  NotHan: string;
  NotHans: number;
  NotHanCount: number;
  Lack: string;
  Lacks: number;
  LackCount: number;
}

export interface Info {
  TextName: string;
  TextLen: number;
  DictName: string;
  DictLen: number;
  Single: boolean;
}

export interface Key {
  Count: number;
  Rate: number;
}

export interface Pair {
  Count: number;
  SameFinger: number;
  DoubleHit: number;
  TribleHit: number;
  SingleSpan: number;
  MultiSpan: number;
  Staggered: number;
  Disturb: number;
  LeftToLeft: number;
  LeftToRight: number;
  RightToLeft: number;
  RightToRight: number;
  DiffFinger: number;
  SameHand: number;
  DiffHand: number;
}
